In [81]:
import numpy as np
import torch
torch.manual_seed(1)
print(torch.__version__)

1.2.0


# base Tenseor

In [2]:
x = torch.Tensor(2,2)
x

tensor([[0., 0.],
        [0., 0.]])

In [3]:
x.type(), x.size(), x.numel()

('torch.FloatTensor', torch.Size([2, 2]), 4)

In [4]:
x2 = torch.Tensor(4,3,2,1)
x2

tensor([[[[1.0504e-05],
          [4.1654e-11]],

         [[1.0621e-05],
          [2.9574e-18]],

         [[6.7333e+22],
          [1.7591e+22]]],


        [[[1.7184e+25],
          [4.3222e+27]],

         [[6.1972e-04],
          [7.2443e+22]],

         [[1.7728e+28],
          [7.0367e+22]]],


        [[[2.9926e+21],
          [1.1050e-05]],

         [[1.0481e-11],
          [6.7126e-07]],

         [[4.3679e-05],
          [1.0978e-05]]],


        [[[1.6535e-04],
          [2.0430e+20]],

         [[2.0567e+20],
          [2.4287e-18]],

         [[7.7052e+31],
          [1.9447e+31]]]])

In [5]:
x2.size(), x2.type(), x2.numel()

(torch.Size([4, 3, 2, 1]), 'torch.FloatTensor', 24)


# Other methods make to Tensor

In [6]:
torch.zeros(4,4), torch.ones(4,4), torch.eye(4,4),torch.rand(4,4), torch.randn(4,4)

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]), tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]), tensor([[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]]), tensor([[0.7576, 0.2793, 0.4031, 0.7347],
         [0.0293, 0.7999, 0.3971, 0.7544],
         [0.5695, 0.4388, 0.6387, 0.5247],
         [0.6826, 0.3051, 0.4635, 0.4550]]), tensor([[-0.6970, -1.1608,  0.6995,  0.1991],
         [ 0.8657,  0.2444, -0.6629,  0.8073],
         [ 1.1017, -0.1759, -2.2456, -1.4465],
         [ 0.0612, -0.6177, -0.7981, -0.1316]]))

In [7]:
x3 = torch.arange(0, 3, step=0.3)
x3

tensor([0.0000, 0.3000, 0.6000, 0.9000, 1.2000, 1.5000, 1.8000, 2.1000, 2.4000,
        2.7000])

In [8]:
x3

tensor([0.0000, 0.3000, 0.6000, 0.9000, 1.2000, 1.5000, 1.8000, 2.1000, 2.4000,
        2.7000])

In [9]:
torch.Tensor([[6,2],[3,4],[5,6]])

tensor([[6., 2.],
        [3., 4.],
        [5., 6.]])

In [10]:
numpy_test = np.array([[5,6],[10,11]])
torch.from_numpy(numpy_test)

tensor([[ 5,  6],
        [10, 11]], dtype=torch.int32)


# Use to array function of Python make Tensor 

In [11]:
x4 = torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])
x4

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [12]:
x4[0:2,:]

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [13]:
x4[1]

tensor([4., 5., 6.])

In [14]:
x4[0,:]

tensor([1., 2., 3.])

In [15]:
x4[0:1,:] = torch.Tensor([62,72,80])
x4

tensor([[62., 72., 80.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]])

In [16]:
x4[1] = torch.Tensor([200,78, 89])
x4

tensor([[ 62.,  72.,  80.],
        [200.,  78.,  89.],
        [  7.,   8.,   9.]])

In [25]:
x5 = torch.split(x4, split_size_or_sections=1,dim=0)
x5

(tensor([[62., 72., 80.]]),
 tensor([[200.,  78.,  89.]]),
 tensor([[7., 8., 9.]]))

In [26]:
torch.cat(x5, dim=1)

tensor([[ 62.,  72.,  80., 200.,  78.,  89.,   7.,   8.,   9.]])

In [27]:
torch.stack(x5, dim=1)

tensor([[[ 62.,  72.,  80.],
         [200.,  78.,  89.],
         [  7.,   8.,   9.]]])

In [28]:
x6 = torch.randn(3,3)

mask  = torch.ByteTensor([[1,0,0],[1,1,1],[0,1,0]])

out = torch.masked_select(x6, mask)

x6, mask, out

..\aten\src\ATen\native\LegacyDefinitions.cpp:48: UserWarning: masked_select received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.


(tensor([[-0.4791,  1.3790,  2.5286],
         [ 0.4107, -0.9880, -0.9081],
         [ 0.5423,  0.1103, -2.2590]]), tensor([[1, 0, 0],
         [1, 1, 1],
         [0, 1, 0]], dtype=torch.uint8), tensor([-0.4791,  0.4107, -0.9880, -0.9081,  0.1103]))


# Reshaping on dimension of Tensor

In [29]:
x7 = torch.zeros(2,2,1)
x7

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]]])

In [30]:
x7.view(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [31]:
x7.view(-1) # -1 = Automatic

tensor([0., 0., 0., 0.])

In [32]:
x7.view(-1,2)

tensor([[0., 0.],
        [0., 0.]])

In [33]:
x7.view(4)

tensor([0., 0., 0., 0.])

In [34]:
x8 = x7.squeeze()
x7, x8

(tensor([[[0.],
          [0.]],
 
         [[0.],
          [0.]]]), tensor([[0., 0.],
         [0., 0.]]))

In [35]:
x8.unsqueeze(0)

tensor([[[0., 0.],
         [0., 0.]]])


# Calculate

In [36]:
x9 = torch.FloatTensor([[10,20,30],[40,50,60]])
x10 = torch.FloatTensor([[1,2,3],[4,5,6]])
x9, x10

(tensor([[10., 20., 30.],
         [40., 50., 60.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]))

In [37]:
x9  + x10, x9.add(x10), torch.add(x9, x10)

(tensor([[11., 22., 33.],
         [44., 55., 66.]]), tensor([[11., 22., 33.],
         [44., 55., 66.]]), tensor([[11., 22., 33.],
         [44., 55., 66.]]))

In [38]:
x10.sub(x9), x9.sub(x10)

(tensor([[ -9., -18., -27.],
         [-36., -45., -54.]]), tensor([[ 9., 18., 27.],
         [36., 45., 54.]]))

In [39]:
x10[1] + 12

tensor([16., 17., 18.])

In [40]:
x9 * x10, x10.mul(x9), torch.mul(x10,x9)

(tensor([[ 10.,  40.,  90.],
         [160., 250., 360.]]), tensor([[ 10.,  40.,  90.],
         [160., 250., 360.]]), tensor([[ 10.,  40.,  90.],
         [160., 250., 360.]]))

In [41]:
x10 * 10

tensor([[10., 20., 30.],
        [40., 50., 60.]])


# Other Calculate

In [45]:
x9.pow(2), torch.pow(x9,2), x9 ** 2

(tensor([[ 100.,  400.,  900.],
         [1600., 2500., 3600.]]), tensor([[ 100.,  400.,  900.],
         [1600., 2500., 3600.]]), tensor([[ 100.,  400.,  900.],
         [1600., 2500., 3600.]]))

In [46]:
x9.sqrt()

tensor([[3.1623, 4.4721, 5.4772],
        [6.3246, 7.0711, 7.7460]])

In [47]:
x10.log(), torch.log(x10)

(tensor([[0.0000, 0.6931, 1.0986],
         [1.3863, 1.6094, 1.7918]]), tensor([[0.0000, 0.6931, 1.0986],
         [1.3863, 1.6094, 1.7918]]))

In [48]:
x9 % 3, x9 / 3

(tensor([[1., 2., 0.],
         [1., 2., 0.]]), tensor([[ 3.3333,  6.6667, 10.0000],
         [13.3333, 16.6667, 20.0000]]))

In [49]:
x9.sum(), x9.max()

(tensor(210.), tensor(60.))

In [50]:
x10.min(), x10.min(0), x10.min(1)

(tensor(1.), torch.return_types.min(
 values=tensor([1., 2., 3.]),
 indices=tensor([0, 0, 0])), torch.return_types.min(
 values=tensor([1., 4.]),
 indices=tensor([0, 0])))

In [51]:
x10.max(1)

torch.return_types.max(
values=tensor([3., 6.]),
indices=tensor([2, 2]))

In [52]:
x9.abs(), x9

(tensor([[10., 20., 30.],
         [40., 50., 60.]]), tensor([[10., 20., 30.],
         [40., 50., 60.]]))

In [53]:
x9[1] = torch.Tensor([-3,3,-10])
x9, x9.abs()

(tensor([[ 10.,  20.,  30.],
         [ -3.,   3., -10.]]), tensor([[10., 20., 30.],
         [ 3.,  3., 10.]]))

In [54]:
value, index = x10.max(dim = 1)
value, index

(tensor([3., 6.]), tensor([2, 2]))

In [55]:
x10.max()

tensor(6.)


# Matrix Calculate

In [56]:
x11 = torch.randn(3,5)
x12 = torch.randn(5,5)
x13 = torch.randn(5,3)
x11, x12, x13

(tensor([[ 0.6067, -0.1383,  0.8310, -0.2477, -0.8029],
         [ 0.2366,  0.2857,  0.6898, -0.6331,  0.8795],
         [-0.6842,  0.4533,  0.2912, -0.8317, -0.5525]]),
 tensor([[ 1.3851, -0.8138, -0.9276,  1.1120,  0.6155],
         [ 0.1938, -2.5832,  0.8539, -2.1021,  0.3476],
         [ 0.0930,  0.6147,  0.7124, -1.7765,  0.3539],
         [ 1.1996, -0.3030, -0.6200, -0.2281, -0.7893],
         [-1.6111, -1.8716,  0.5431,  0.6607,  2.2952]]),
 tensor([[ 0.6355, -1.0901, -0.2380],
         [ 0.6905,  0.4646, -0.7559],
         [-2.0501,  0.6842, -0.8003],
         [-0.3738,  1.4904, -1.2968],
         [-0.3243,  0.3105, -0.3423]]))

In [57]:
1.6200 * 1.1375  + 0.3436 * -0.9347 + -0.9112 * 1.3267 + -0.9952 *  -0.0336 + 0.7455 * 1.3210

1.33094226

In [58]:
torch.mm(x11,x12), x11.mm(x12)

(tensor([[ 1.8873,  1.9522, -0.3714, -0.9849, -1.0280],
         [-1.7291, -1.9607,  1.3861, -0.8375,  3.0073],
         [-0.9403,  0.8509,  1.4448, -2.4062, -0.7722]]),
 tensor([[ 1.8873,  1.9522, -0.3714, -0.9849, -1.0280],
         [-1.7291, -1.9607,  1.3861, -0.8375,  3.0073],
         [-0.9403,  0.8509,  1.4448, -2.4062, -0.7722]]))

In [59]:
x11.mm(x12).mm(x13)

tensor([[ 4.0103e+00, -3.1916e+00,  1.3142e-03],
        [-5.9565e+00,  1.6081e+00,  8.4113e-01],
        [-1.8220e+00, -1.4170e+00,  1.8090e+00]])

In [60]:
x11.mm(x12).mm(x13).mm(x11)

tensor([[ 1.6771, -1.4659,  1.1313,  1.0260, -6.0277],
        [-3.8089,  1.6645, -3.5958, -0.2421,  5.7323],
        [-2.6783,  0.6672, -1.9648, -0.1562, -0.7828]])

In [61]:
x14 = torch.randn(3, 4)
v = torch.randn(4)

x14, v

(tensor([[ 0.6976,  1.4117,  2.1331, -0.1602],
         [ 0.3615,  0.3725, -0.3054, -0.6147],
         [-0.9315, -1.8460,  0.5781, -0.9483]]),
 tensor([ 0.0943,  0.6352, -0.6054, -0.2838]))

In [62]:
 -0.4594 * 0.6623 + -1.1798 * 0.2916 +0.3812 * 0.0409+ -0.0064 *  -1.1908

-0.6250781

In [63]:
torch.mv(x14,v), x14.mv(v)

(tensor([-0.2833,  0.6300, -1.3412]), tensor([-0.2833,  0.6300, -1.3412]))

In [64]:
x15 = torch.randn(10,3,4)
x16 = torch.randn(10,4,5)

torch.bmm(x15, x16).size()

torch.Size([10, 3, 5])

In [65]:
torch.bmm(x15, x16)

tensor([[[ 6.9434e-01,  6.0964e+00,  1.7202e+00, -3.8169e+00, -2.9654e+00],
         [ 1.8189e+00, -1.8705e+00,  6.2631e-01, -9.5523e-01, -1.1729e+00],
         [-2.5354e-01,  3.2282e+00,  4.7611e-01, -1.6111e+00, -5.8421e-01]],

        [[ 2.3530e+00, -2.3066e+00, -4.9446e-01,  1.3988e+00,  2.5245e-01],
         [ 1.9755e+00, -5.1293e-01,  3.7283e+00, -3.7956e-01, -2.2084e+00],
         [-3.9758e+00,  4.6995e+00,  3.3093e+00, -2.5224e+00,  4.1832e-02]],

        [[ 1.7741e+00, -1.5162e+00,  1.4017e+00, -2.0276e+00,  3.3163e-01],
         [-6.6708e-01,  5.0203e-01,  2.2442e-01,  1.3185e-01,  4.8007e-01],
         [ 2.4549e+00, -1.1149e+00,  1.3117e+00, -2.3741e+00, -1.4196e+00]],

        [[-8.7446e-01,  1.2346e+00,  3.4694e+00, -2.1092e+00,  2.4723e+00],
         [ 8.1480e-02,  2.6153e-01, -5.5364e-01, -3.4624e-03,  4.2223e-01],
         [-6.7161e-01,  7.2215e-01,  3.6370e-01, -1.0077e-01,  3.6898e-01]],

        [[ 2.7225e+00,  1.7054e+00,  4.5947e+00,  4.8942e+00, -6.9139e+00],
    

In [66]:
x17 = torch.randn(2,2)
x18 = torch.randn(2,2)

torch.dot(x17.view(-1), x18.view(-1)), x17, x18

(tensor(-0.9199), tensor([[ 1.0819, -0.3676],
         [-0.2451,  1.0594]]), tensor([[-1.1824, -1.0863],
         [ 1.5532,  0.3215]]))

In [67]:
1.7038 *  -0.6295 + -1.6000 *  -1.0304 +  1.4366 * -0.0231 + -0.9917 * 0.1807

0.3637122500000002

In [68]:
torch.dot(x17.view(-1), x18.view(-1))

tensor(-0.9199)

In [69]:
x19  = torch.rand(3,4)

x19, x19.t()

(tensor([[0.4929, 0.8539, 0.4242, 0.0949],
         [0.1302, 0.3532, 0.3893, 0.5571],
         [0.3879, 0.6845, 0.3337, 0.8670]]), tensor([[0.4929, 0.1302, 0.3879],
         [0.8539, 0.3532, 0.6845],
         [0.4242, 0.3893, 0.3337],
         [0.0949, 0.5571, 0.8670]]))

In [70]:
u, s, v = torch.svd(x19)
u, s, v, x19

(tensor([[-0.5665,  0.8205, -0.0769],
         [-0.4313, -0.3747, -0.8207],
         [-0.7022, -0.4318,  0.5661]]),
 tensor([1.6865, 0.6069, 0.1842]),
 tensor([[-0.3603,  0.3100,  0.4061],
         [-0.6622,  0.4492,  0.1732],
         [-0.3810,  0.0957, -0.8858],
         [-0.5353, -0.8324,  0.1428]]),
 tensor([[0.4929, 0.8539, 0.4242, 0.0949],
         [0.1302, 0.3532, 0.3893, 0.5571],
         [0.3879, 0.6845, 0.3337, 0.8670]]))

In [71]:
torch.dist(x19, torch.mm(torch.mm(u, torch.diag(s)), v.t()))

tensor(4.8170e-07)


# Tensor Data Type

In [72]:
x20 = torch.rand(2,2)
x20

tensor([[0.6148, 0.3463],
        [0.9456, 0.6276]])

In [73]:
x20  = torch.LongTensor([1,1])
x20

tensor([1, 1])

In [74]:
x20.float()

tensor([1., 1.])

In [75]:
x20.double()

tensor([1., 1.], dtype=torch.float64)

In [76]:
x20.byte()

tensor([1, 1], dtype=torch.uint8)

In [77]:
x20

tensor([1, 1])

In [78]:
x20 = x20.cpu()
x20

tensor([1, 1])

In [79]:
x20.numpy()

array([1, 1], dtype=int64)

In [80]:
torch.from_numpy(np.random.rand(3,2))

tensor([[0.2762, 0.6077],
        [0.3506, 0.6249],
        [0.0808, 0.2736]], dtype=torch.float64)