In [1]:
import torch
from torch.autograd import Variable


# Tensor VS Variable

In [2]:
tensor = torch.rand(2,2,)
x = Variable(tensor, requires_grad=True)

tensor, x

(tensor([[0.9386, 0.6575],
         [0.8530, 0.2335]]), tensor([[0.9386, 0.6575],
         [0.8530, 0.2335]], requires_grad=True))

In [3]:
x.sum(), x.sqrt(), x**2, x

(tensor(2.6827, grad_fn=<SumBackward0>), tensor([[0.9688, 0.8109],
         [0.9236, 0.4833]], grad_fn=<SqrtBackward>), tensor([[0.8809, 0.4323],
         [0.7277, 0.0545]], grad_fn=<PowBackward0>), tensor([[0.9386, 0.6575],
         [0.8530, 0.2335]], requires_grad=True))


# Variable

In [4]:
x.data

tensor([[0.9386, 0.6575],
        [0.8530, 0.2335]])

In [5]:
x.requires_grad, x.grad, x.grad_fn, x.volatile

C:\Users\hwnau\.conda\envs\cuda\lib\site-packages\ipykernel_launcher.py:1: UserWarning: volatile was removed (Variable.volatile is always False)
  """Entry point for launching an IPython kernel.


(True, None, None, False)

In [6]:
x = Variable(torch.FloatTensor([3]), requires_grad=True)

y = x**3 + 3

z  = Variable(torch.FloatTensor([5]))

x.requires_grad, y.requires_grad, z.requires_grad, y

(True, True, False, tensor([30.], grad_fn=<AddBackward0>))

In [7]:
y.grad_fn.next_functions[0][0]

In [8]:
y.backward()

In [9]:
x, x.grad

(tensor([3.], requires_grad=True), tensor([27.]))

In [10]:
x.grad, x.grad.data.zero_(), x.grad

(tensor([0.]), tensor([0.]), tensor([0.]))

In [11]:
x1 = Variable(torch.ones(2), requires_grad = True)
x2 = Variable(torch.ones(2))

In [12]:
y = x1 * 2 + x2
y

tensor([3., 3.], grad_fn=<AddBackward0>)

In [13]:
y.backward(torch.Tensor([1,1]))

In [14]:
x1.grad

tensor([2., 2.])

In [15]:
x2.grad

In [16]:
x1.grad.data.zero_()

tensor([0., 0.])